### ISSUE TITLE
Main Server Error: No router instance found.

### ISSUE THREAD

**Issue by GustavPS** [GustavPS/Dose#81]
**Describe the bug**
Main server crashes when main token doesn't exist(?)

**To Reproduce**
Unclear, maybe remove access token

**Expected behavior**
Doesn't crash

**Logs**
```
Main token does not exist
/node_modules/next/dist/client/router.js:117
        throw new Error(message);
              ^

Error: No router instance found.
You should only use "next/router" on the client side of your app.

    at getRouter (/node_modules/next/dist/client/router.js:117:15)
    at Object.singletonRouter.<computed> [as push] (/node_modules/next/dist/client/router.js:94:24)
    at Object.callback (/.next/server/chunks/551.js:42:29)
    at Timeout._onTimeout (/node_modules/node-async-locks/lib/async-lock.js:95:15)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

```

**Comment by GustavPS** [comment]
Seems to happen every time you try to play next episode in a show (probably because after that the token is expired or something like that)

**Comment by GustavPS** [comment]
Happens everytime you go directly to a Movie/Episode directly via the URL
