### ISSUE TITLE
Main server crash api/requests/expected

### ISSUE THREAD

**Issue by GustavPS** [GustavPS/Dose#88]
**Describe the bug**
Main server crashes when network request to `api/requests/expected` endpoint on content server is unreachable 

**Expected behavior**
Doesn't crash and handle it as not expected

**Logs**
FetchError: request to http://192.168.1.2:3001/api/requests/expected?id=e44017e0084c8fc6be349233ce58edb13c767044794b6377de failed, reason: connect EHOSTUNREACH 192.168.1.2:3001
    at ClientRequest.<anonymous> (/node_modules/next/dist/compiled/node-fetch/index.js:1:64142)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:442:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH'
}

Node.js v17.7.2

**Comment by GustavPS** [comment]
Related crash:
`TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/node_modules/next/dist/compiled/node-fetch/index.js:1:61917)
    at /node_modules/next/dist/compiled/node-fetch/index.js:1:63448
    at new Promise (<anonymous>)
    at Function.fetch [as default] (/node_modules/next/dist/compiled/node-fetch/index.js:1:63382)
    at fetchWithAgent (/node_modules/next/dist/server/node-polyfill-fetch.js:38:39)
    at /.next/server/pages/api/servers/register.js:45:9
    at new Promise (<anonymous>)
    at handle (/.next/server/pages/api/servers/register.js:44:12)
    at Object.apiResolver (/node_modules/next/dist/server/api-utils/node.js:182:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.7.2`
